require "rails_helper"

RSpec.describe "Preferences selection flow", type: :request do
  let(:user) { User.create!(username: "testuser", email: "test@example.com", password: "password") }
  let!(:coffee) { Preference.create!(name: "coffee") }
  let!(:tea) { Preference.create!(name: "tea") }

  before do
    # Log the user in
    post login_path, params: { username: user.username, password: "password" }

    # Ensure controller sees the logged-in user
    allow_any_instance_of(ApplicationController).to receive(:current_user).and_return(user)
  end

  # Default params exactly matching the real form generated by Rails
  def form_params(overrides = {})
    {
      "likes" => [],
      "dislikes" => [],
      "new_like" => "",
      "new_dislike" => "",
      "commit" => "Continue"
    }.merge(overrides)
  end

  it "user selects a like" do
    post bulk_save_preferences_path, params: form_params(
      "likes" => [coffee.id.to_s]
    )

    up = UserPreference.find_by(user: user, preference: coffee)
    expect(up).not_to be_nil
    expect(up.category).to eq("like")
  end

  it "user selects a dislike" do
    post bulk_save_preferences_path, params: form_params(
      "dislikes" => [tea.id.to_s]
    )

    up = UserPreference.find_by(user: user, preference: tea)
    expect(up).not_to be_nil
    expect(up.category).to eq("dislike")
  end

  it "user adds a custom preference" do
    post bulk_save_preferences_path, params: form_params(
      "new_like" => "matcha"
    )

    pref = Preference.find_by(name: "matcha")
    expect(pref).not_to be_nil

    up = UserPreference.find_by(user: user, preference: pref)
    expect(up).not_to be_nil
    expect(up.category).to eq("like")
  end
end